[package]
name = "dnsless-server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "dnsless-server"
path = "src/main.rs"

[dependencies]
dnsless-common = { path = "../common" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
log = "0.4"
env_logger = "0.11"
get_if_addrs = "0.5"
tungstenite = "0.26"

[dev-dependencies]
tempfile = "3"
